### ISSUE TITLE
Plugin is not working on my server

### ISSUE THREAD

**Issue by KlpefFreeMber** [Cyanox62/SCPSwap#1]
![image](https://user-images.githubusercontent.com/43294403/75690085-3d0cd380-5cdd-11ea-9ad0-1371c808066a.png)

![image](https://user-images.githubusercontent.com/43294403/75690278-83fac900-5cdd-11ea-9a80-9af3b15a4543.png)

Is there something wrong with my action?

**Comment by Cyanox62** [comment]
You need to put a period in front of the command.

`.scpswap number`
